inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - !ruby/regexp /(vendor|bundle|bin|db)\/.*/
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.2
  # https://github.com/bbatsov/rubocop/blob/master/manual/caching.md
  # https://github.com/bbatsov/rubocop/blob/e8680418b351491e111a18cf5b453fc07a3c5239/config/default.yml#L60-L77
  UseCache: true
  CacheRootDirectory: tmp

Rails:
  Enabled: true

Style/NumericPredicate:
  Enabled: false

# Rubocop options don't align with code-style, which allows alias.
# https://github.com/bbatsov/ruby-style-guide/pull/383
# https://github.com/bbatsov/rubocop/issues/1460
# see https://github.com/bbatsov/ruby-style-guide#alias-method-lexically
# vs. https://github.com/bbatsov/ruby-style-guide#alias-method
Style/Alias:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

# SupportedStyles: line_count_based, semantic, braces_for_chaining
Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: line_count_based

Style/MissingElse:
  Enabled: true
  EnforcedStyle: case

Style/EmptyElse:
  EnforcedStyle: empty

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  Enabled: true

Style/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: ignore_implicit

Style/IndentHash:
  EnforcedStyle: consistent

Style/IndentationWidth:
  Width: 2

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/FirstParameterIndentation:
  EnforcedStyle: special_for_inner_method_call_in_parentheses

Style/ExtraSpacing:
  Enabled: true

Lint/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: either

Lint/EndAlignment:
  Enabled: true

Style/SpaceAfterColon:
  Enabled: true

Style/SpaceAfterComma:
  Enabled: true

Style/SpaceAfterNot:
  Enabled: true

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SpaceBeforeBlockBraces:
  Enabled: false
  # EnforcedStyle: space

Style/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  # Space between { and |. Overrides EnforcedStyle if there is a conflict.
  SpaceBeforeBlockParameters: true

Style/SpaceInsideBrackets:
  Enabled: true

Style/SpaceInsideParens:
  Enabled: true

Style/EmptyLines:
  Enabled: true

Style/EmptyLinesAroundAccessModifier:
  Enabled: true

Style/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines

Style/EmptyLinesAroundMethodBody:
  Enabled: true

Style/EmptyLineBetweenDefs:
  Enabled: true

Style/LeadingCommentSpace:
  Enabled: true

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingWhitespace:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': ()
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': ()
    '%W': ()
    '%x': ()

Style/StringLiterals:
  # EnforcedStyle: single_quotes
  Enabled: false

Style/StringLiteralsInInterpolation:
  # EnforcedStyle: single_quotes
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  # AllowSafeAssignment: true
  # accepts = in condition surrounded with braces, e.g. if (test = 10)
  # accepts []= in condition surrounded with braces, e.g. if (test[0] = 10)
  Enabled: true

Style/VariableNumber:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpaceInLambdaLiteral:
  EnforcedStyle: require_no_space

Style/DoubleNegation:
  Enabled: false

Metrics/LineLength:
  Max: 100
